use std::{env, fs, path::PathBuf};

/// Tauri validates every configured resource while compiling the build script.
///
/// dist/ is intentionally ignored because it is generated by Vite. A plain
/// cargo test on a fresh checkout should still compile the Rust workspace, so
/// create a clearly marked placeholder for that development-only path.
/// Packaging runs pnpm build first and replaces it with the real bundle.
fn ensure_frontend_dist() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let dist = manifest_dir.join("..").join("dist");
    if dist.is_dir() {
        return;
    }

    fs::create_dir_all(&dist).expect("create frontend dist placeholder");
    fs::write(
        dist.join(".dsh-studio-dev-placeholder"),
        "Generated by src-tauri/build.rs for Rust-only development builds.\n",
    )
    .expect("write frontend dist placeholder");
    println!("cargo:warning=frontend dist/ is missing; created a development placeholder");
}

fn main() {
    ensure_frontend_dist();
    println!("cargo:rerun-if-env-changed=DSH_STUDIO_EDITION");
    let edition = std::env::var("DSH_STUDIO_EDITION").unwrap_or_else(|_| "lite".into());
    println!("cargo:rustc-env=DSH_STUDIO_EDITION={edition}");
    tauri_build::build();
}
