# typed: strict
# frozen_string_literal: true

# Generated by packaging/generate.mjs — edit that script, not this file.
cask "dsh-studio" do
  arch arm: "aarch64", intel: "x64"

  version "0.9.9"
  sha256 arm:   "4947ed42b5237fb713ac84994c1c3c9409615a64aebcc10cc8d86816de3d2d22",
         intel: "185c85884948796f4b9a5e9181e7121c7477df07f530f30de61ac44662aed355"

  url "https://github.com/Moresyl/dsh-studio/releases/download/v#{version}/DSH.Studio_#{version}_#{arch}.dmg"
  name "DSH Studio"
  desc "Native desktop shell for DeepSeek Harness"
  homepage "https://github.com/Moresyl/dsh-studio"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Tauri 2 supports Catalina and later. The binaries are tagged lower than that
  # — 11.0 on arm64, 10.13 on Intel — but the tag is the linker's deployment
  # target, not a claim that the webview underneath it works, so the framework's
  # floor is the one worth declaring.
  depends_on macos: ">= :catalina"

  app "DSH Studio.app"

  # The application's own directory is named after the binary rather than the
  # bundle identifier, because it comes from the cross-platform data path and not
  # from Tauri. It holds the harness and any Node runtime the app downloaded, so
  # it is by far the largest thing to reclaim — a few hundred megabytes.
  #
  # ~/.dsh is deliberately absent. The harness owns that directory and shares it
  # with its own CLI, so removing it here would take a user's harness
  # configuration with an app they merely stopped using.
  zap trash: [
    "~/Library/Application Support/dsh-studio",
    "~/Library/Caches/io.github.moresyl.dshstudio",
    "~/Library/HTTPStorages/io.github.moresyl.dshstudio",
    "~/Library/Preferences/io.github.moresyl.dshstudio.plist",
    "~/Library/Saved Application State/io.github.moresyl.dshstudio.savedState",
    "~/Library/WebKit/io.github.moresyl.dshstudio",
  ]
end
